### PR TITLE
Added time zone support in query builder

### PR DESCRIPTION
**Pull request by adeliz**

### CODE REVIEW

**Comment by jsabin** [comment]
I think I'm missing something here. I see the setting and getting of Timezone, but I don't see how its being used. Absolute times are milliseconds from Epoch so I assume you are using this for relative times? Is there more code that is not part of this pull request?

**Comment by FrEaKmAn** [comment]
But you could also use timezone for absolute times. For example, select from 1.1.2015 until 31.12.2015, group by a day. Timezone will acknowledge daylight saving time.

Btw, wouldn't make more sense to pass TimeZone instance to setTimeZone method instead of a string?

**Comment by adeliz** [comment]
The goal is just to provide the *time_zone* parameter as in KairosDB Rest API.
```json
{
	"start_absolute": 784041330,
	"end_absolute": 788879730,
	"time_zone": "Etc/GMT-6",
	"metrics": [
		{
			"name": "temperature",
			"aggregators": [
				{
					"name" : "avg",
					"sampling": {
						"value": 1,
						"unit": "days"
					}
				}
			]
		}
	]
}
```
The parameter is used by aggregators. For example, a daily average will be different for different timezones.

I chose to pass the TimeZone ID as a string but I can pass a TimeZone instance instead.

**Comment by FrEaKmAn** [comment]
But if I'm not mistaken, time_zone has to be passed to aggregators...

**Comment by adeliz** [comment]
I don't think so.
if you look at [GsonParser](https://github.com/kairosdb/kairosdb/blob/6b2938f150788b5725ae3c0660ac0df91b562650/src/main/java/org/kairosdb/core/http/rest/json/GsonParser.java#L522-L523), *time_zone* seems to be a a global parameter.
Then, it is used by [aggregators](https://github.com/kairosdb/kairosdb/blob/6b2938f150788b5725ae3c0660ac0df91b562650/src/main/java/org/kairosdb/core/http/rest/json/GsonParser.java#L202).
Do you confirm?

**Comment by FrEaKmAn** [comment]
based on this, you need to pass it to aggregators.. unless if something changed..

https://groups.google.com/d/topic/kairosdb-group/WsD5XLDhYr8/discussion

**Comment by adeliz** [comment]
In fact, I dug a little bit deeper in the code, and after some tests, I would say that both work.
If both are presents, *time_zone* as aggregator parameter will overwrite *time_zone* as global parameter.

If I refer to the google groups discussion above, set the *time_zone* parameter as global seems the best choice.
Do I need to modify the pull request?

**Comment by jsabin** [comment]
Sorry. I totally missed the fact that you were just added the time zone to the query since its now supported in Kairos. I guess I was ready too many emails too fast.

**Comment by jsabin** [comment]
I added timezone as an object rather than a string. Thanks for pointing out this missing feature.

**Pull request closed without merging**
