### PR TITLE
Gzip support

### PR DESCRIPTION
**Pull request by vimal3271**
Added support for gzip in kairosdb java client

### CODE REVIEW

**Comment by martin-g** [comment]
Is this released ? I do not see the new `MetricBuilder#setUseCompression(boolean)` method in 2.2.0

**Comment by martin-g** [comment]
Any ETA when this improvement will be released ?

**Comment by vimal3271** [comment]
This is not released. The owner of this repository has to release new build.

**Comment by martin-g** [comment]
@jsabin  A release will be appreciated!

**Pull request merged**
